  on: push

  jobs:
      list_buckets:
        runs-on: ubuntu-latest
        steps:
          - name: prints
            env:
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              AWS_DEFAULT_REGION: eu-west-1
            run: |
              aws s3 ls
            
